name: Test

env:
  NEXT_PUBLIC_SANITY_PROJECT_ID: 27cruzhr
  NEXT_PUBLIC_SANITY_DATASET: production
#   SANITY_API_READ_TOKEN: ${{ vars.SANITY_API_READ_TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"

      - name: Install PNPM
        run: |
          sudo corepack enable
          corepack prepare pnpm@9.12.3 --activate
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build